// SRD 5.1 spells, organized by level. Each spell lists which classes can
// learn/prepare it (by class key) so the wizard can filter correctly.
// `school` uses standard 5e schools. `concentration`/`ritual` are booleans.

export const CANTRIPS = [
  { key: 'acid-splash', name: 'Acid Splash', level: 0, school: 'Conjuration', classes: ['sorcerer', 'wizard'], concentration: false, ritual: false, castingTime: '1 action', range: '60 feet', duration: 'Instantaneous', description: 'You hurl a bubble of acid. Choose one creature within range, or two creatures within 5 feet of each other. A target must succeed on a Dexterity save or take 1d6 acid damage.' },
  { key: 'blade-ward', name: 'Blade Ward', level: 0, school: 'Abjuration', classes: ['bard', 'sorcerer', 'warlock', 'wizard'], concentration: false, ritual: false, castingTime: '1 action', range: 'Self', duration: '1 round', description: 'You extend your hand and trace a sigil of warding in the air. Until the end of your next turn, you have resistance against bludgeoning, piercing, and slashing damage from weapon attacks.' },
  { key: 'chill-touch', name: 'Chill Touch', level: 0, school: 'Necromancy', classes: ['sorcerer', 'warlock', 'wizard'], concentration: false, ritual: false, castingTime: '1 action', range: '120 feet', duration: '1 round', description: 'You create a ghostly skeletal hand. Make a ranged spell attack; on a hit the target takes 1d8 necrotic damage and can\u2019t regain hit points until the start of your next turn.' },
  { key: 'dancing-lights', name: 'Dancing Lights', level: 0, school: 'Evocation', classes: ['bard', 'sorcerer', 'wizard'], concentration: true, ritual: false, castingTime: '1 action', range: '120 feet', duration: 'Concentration, up to 1 minute', description: 'You create up to four torch-sized lights within range, making them appear as torches, lanterns, or glowing orbs that hover in the air for the duration.' },
  { key: 'druidcraft', name: 'Druidcraft', level: 0, school: 'Transmutation', classes: ['druid'], concentration: false, ritual: false, castingTime: '1 action', range: '30 feet', duration: 'Instantaneous', description: 'You create one of several minor nature effects: predicting weather, making a flower bloom, creating a harmless sensory effect, or instantly snuffing a small flame.' },
  { key: 'eldritch-blast', name: 'Eldritch Blast', level: 0, school: 'Evocation', classes: ['warlock'], concentration: false, ritual: false, castingTime: '1 action', range: '120 feet', duration: 'Instantaneous', description: 'A beam of crackling energy streaks toward a creature within range. Make a ranged spell attack; on a hit the target takes 1d10 force damage. The spell creates more than one beam at higher levels.' },
  { key: 'fire-bolt', name: 'Fire Bolt', level: 0, school: 'Evocation', classes: ['sorcerer', 'wizard'], concentration: false, ritual: false, castingTime: '1 action', range: '120 feet', duration: 'Instantaneous', description: 'You hurl a mote of fire. Make a ranged spell attack against the target; on a hit it takes 1d10 fire damage. A flammable object hit by this spell ignites if not worn or carried.' },
  { key: 'guidance', name: 'Guidance', level: 0, school: 'Divination', classes: ['cleric', 'druid'], concentration: true, ritual: false, castingTime: '1 action', range: 'Touch', duration: 'Concentration, up to 1 minute', description: 'You touch one willing creature. Once before the spell ends, the target can roll a d4 and add the number rolled to one ability check of its choice.' },
  { key: 'light', name: 'Light', level: 0, school: 'Evocation', classes: ['bard', 'cleric', 'sorcerer', 'wizard'], concentration: false, ritual: false, castingTime: '1 action', range: 'Touch', duration: '1 hour', description: 'You touch one object that is no larger than 10 feet in any dimension. Until the spell ends, the object sheds bright light in a 20-foot radius.' },
  { key: 'mage-hand', name: 'Mage Hand', level: 0, school: 'Conjuration', classes: ['bard', 'sorcerer', 'warlock', 'wizard'], concentration: false, ritual: false, castingTime: '1 action', range: '30 feet', duration: '1 minute', description: 'A spectral, floating hand appears at a point you choose within range, lasting for the duration. The hand can manipulate objects, open doors, and carry up to 10 pounds.' },
  { key: 'mending', name: 'Mending', level: 0, school: 'Transmutation', classes: ['bard', 'cleric', 'druid', 'sorcerer', 'wizard'], concentration: false, ritual: false, castingTime: '1 minute', range: 'Touch', duration: 'Instantaneous', description: 'This spell repairs a single break or tear in an object you touch, such as a torn cloak or a broken key, leaving no trace of the former damage.' },
  { key: 'message', name: 'Message', level: 0, school: 'Transmutation', classes: ['bard', 'sorcerer', 'wizard'], concentration: false, ritual: false, castingTime: '1 action', range: '120 feet', duration: '1 round', description: 'You point your finger toward a creature within range and whisper a message. The target hears the message and can reply in a whisper only you can hear.' },
  { key: 'minor-illusion', name: 'Minor Illusion', level: 0, school: 'Illusion', classes: ['bard', 'sorcerer', 'warlock', 'wizard'], concentration: false, ritual: false, castingTime: '1 action', range: '30 feet', duration: '1 minute', description: 'You create a sound or an image of an object within range that lasts for the duration. The illusion ends if you dismiss it as an action or cast this spell again.' },
  { key: 'poison-spray', name: 'Poison Spray', level: 0, school: 'Conjuration', classes: ['druid', 'sorcerer', 'warlock', 'wizard'], concentration: false, ritual: false, castingTime: '1 action', range: '10 feet', duration: 'Instantaneous', description: 'You extend your hand toward a creature within range and project a puff of noxious gas. The target must succeed on a Constitution saving throw or take 1d12 poison damage.' },
  { key: 'prestidigitation', name: 'Prestidigitation', level: 0, school: 'Transmutation', classes: ['bard', 'sorcerer', 'warlock', 'wizard'], concentration: false, ritual: false, castingTime: '1 action', range: '10 feet', duration: 'Up to 1 hour', description: 'This spell is a minor magical trick that novice spellcasters use for practice, creating a variety of harmless sensory effects like sparks, odors, or color changes.' },
  { key: 'produce-flame', name: 'Produce Flame', level: 0, school: 'Conjuration', classes: ['druid'], concentration: false, ritual: false, castingTime: '1 action', range: 'Self', duration: '10 minutes', description: 'A flickering flame appears in your hand, casting light, and can be hurled to make a ranged spell attack dealing 1d8 fire damage.' },
  { key: 'resistance', name: 'Resistance', level: 0, school: 'Abjuration', classes: ['cleric', 'druid'], concentration: true, ritual: false, castingTime: '1 action', range: 'Touch', duration: 'Concentration, up to 1 minute', description: 'You touch one willing creature. Once before the spell ends, the target can roll a d4 and add the number rolled to one saving throw of its choice.' },
  { key: 'sacred-flame', name: 'Sacred Flame', level: 0, school: 'Evocation', classes: ['cleric'], concentration: false, ritual: false, castingTime: '1 action', range: '60 feet', duration: 'Instantaneous', description: 'Flame-like radiance descends on a creature you can see within range. The target must succeed on a Dexterity saving throw or take 1d8 radiant damage. This spell ignores cover.' },
  { key: 'shillelagh', name: 'Shillelagh', level: 0, school: 'Transmutation', classes: ['druid'], concentration: false, ritual: false, castingTime: '1 bonus action', range: 'Touch', duration: '1 minute', description: 'The wood of a club or quarterstaff you are holding is imbued with nature\u2019s power, using your spellcasting ability for attack and damage rolls and dealing 1d8 damage on a hit.' },
  { key: 'shocking-grasp', name: 'Shocking Grasp', level: 0, school: 'Evocation', classes: ['sorcerer', 'wizard'], concentration: false, ritual: false, castingTime: '1 action', range: 'Touch', duration: 'Instantaneous', description: 'Lightning springs from your hand to deliver a shock to a creature you try to touch. The target takes 1d8 lightning damage and can\u2019t take reactions until its next turn.' },
  { key: 'spare-the-dying', name: 'Spare the Dying', level: 0, school: 'Necromancy', classes: ['cleric'], concentration: false, ritual: false, castingTime: '1 action', range: 'Touch', duration: 'Instantaneous', description: 'You touch a living creature that has 0 hit points. The creature becomes stable, neither gaining nor losing hit points.' },
  { key: 'thaumaturgy', name: 'Thaumaturgy', level: 0, school: 'Transmutation', classes: ['cleric'], concentration: false, ritual: false, castingTime: '1 action', range: '30 feet', duration: 'Up to 1 minute', description: 'You manifest a minor wonder, a sign of supernatural power, within range: your voice booms, flames flicker, ground trembles, or doors swing open or closed.' },
  { key: 'true-strike', name: 'True Strike', level: 0, school: 'Divination', classes: ['bard', 'sorcerer', 'warlock', 'wizard'], concentration: true, ritual: false, castingTime: '1 action', range: '30 feet', duration: 'Concentration, up to 1 round', description: 'You extend your hand and point a finger at a target in range. Your magic grants you a brief insight into the target\u2019s defenses, giving you advantage on your next attack roll against it before the end of your next turn.' },
  { key: 'vicious-mockery', name: 'Vicious Mockery', level: 0, school: 'Enchantment', classes: ['bard'], concentration: false, ritual: false, castingTime: '1 action', range: '60 feet', duration: 'Instantaneous', description: 'You unleash a string of insults laced with subtle enchantments at a creature you can see within range. If it can hear you, it takes 1d4 psychic damage and has disadvantage on its next attack roll before the end of its next turn.' },
];
