// Part 2 of class data. Concatenated into CLASSES in classes.js via append.

export const CLASSES_PART_2 = [
  {
    key: 'monk',
    name: 'Monk',
    hitDie: 8,
    savingThrows: ['strength', 'dexterity'],
    armorProficiencies: [],
    weaponProficiencies: ['Simple weapons', 'Shortswords'],
    toolProficiencies: ["One type of artisan's tools or musical instrument"],
    skillChoices: { count: 2, options: ['acrobatics', 'athletics', 'history', 'insight', 'religion', 'stealth'] },
    startingEquipment: {
      choices: [
        { options: [{ items: ['A shortsword'] }, { items: ['Any simple weapon'] }] },
        { options: [{ items: ['A dungeoneer\u2019s pack'] }, { items: ['An explorer\u2019s pack'] }] },
      ],
      fixed: ['10 darts'],
    },
    spellcasting: null,
    features: [
      { level: 1, name: 'Unarmored Defense', description: 'While not wearing armor or wielding a shield, your AC equals 10 + Dexterity modifier + Wisdom modifier.' },
      { level: 1, name: 'Martial Arts', description: 'Your practice of martial arts gives you mastery of combat styles that use unarmed strikes and monk weapons, using Dexterity instead of Strength and a bonus-action unarmed strike.' },
      { level: 2, name: 'Ki', description: 'You gain access to ki points that fuel Flurry of Blows, Patient Defense, and Step of the Wind.' },
      { level: 2, name: 'Unarmored Movement', description: 'Your speed increases while you aren\u2019t wearing armor or wielding a shield, and improves further at higher levels.' },
      { level: 3, name: 'Monastic Tradition', description: 'Choose a monastic tradition that you study.', isSubclassChoice: true },
      { level: 3, name: 'Deflect Missiles', description: 'You can use your reaction to deflect or catch a missile when hit by a ranged weapon attack, reducing the damage and potentially throwing it back.' },
      { level: 4, name: 'Slow Fall', description: 'You can use your reaction when you fall to reduce falling damage you take.' },
      { level: 5, name: 'Extra Attack', description: 'You can attack twice, instead of once, whenever you take the Attack action on your turn.' },
      { level: 5, name: 'Stunning Strike', description: 'You can spend 1 ki point to attempt to stun a creature you hit with a melee weapon attack.' },
      { level: 6, name: 'Ki-Empowered Strikes', description: 'Your unarmed strikes count as magical for the purpose of overcoming resistance and immunity to nonmagical attacks.' },
      { level: 7, name: 'Evasion', description: 'When subjected to an effect allowing a Dexterity save for half damage, you take no damage on a success and only half on a failure.' },
      { level: 7, name: 'Stillness of Mind', description: 'You can use your action to end one effect on yourself that is causing you to be charmed or frightened.' },
      { level: 9, name: 'Unarmored Movement Improvement', description: 'You gain the ability to move along vertical surfaces and across liquids without falling.' },
      { level: 10, name: 'Purity of Body', description: 'Your mastery of the ki flowing through you makes you immune to disease and poison.' },
      { level: 13, name: 'Tongue of the Sun and Moon', description: 'You can understand all spoken languages, and any creature that can understand a language can understand you.' },
      { level: 14, name: 'Diamond Soul', description: 'You gain proficiency in all saving throws. You can also spend 1 ki point to reroll a failed save.' },
      { level: 15, name: 'Timeless Body', description: 'Your ki sustains you so that you suffer none of the frailty of old age, and you don\u2019t need food or water.' },
      { level: 18, name: 'Empty Body', description: 'You can spend 4 ki points to become invisible for 1 minute, or 8 ki points to cast astral projection.' },
      { level: 20, name: 'Perfect Self', description: 'When you roll initiative and have no ki points remaining, you regain 4 ki points.' },
    ],
    subclasses: [
      {
        key: 'way-of-the-open-hand',
        name: 'Way of the Open Hand',
        features: [
          { level: 3, name: 'Open Hand Technique', description: 'You can impose conditions on a creature when you hit it with one of the attacks granted by Flurry of Blows.' },
          { level: 6, name: 'Wholeness of Body', description: 'You can use your action to regain a number of hit points equal to three times your monk level.' },
          { level: 11, name: 'Tranquility', description: 'You can enter a special meditation at the end of a long rest that grants you the effect of a sanctuary spell.' },
          { level: 17, name: 'Quivering Palm', description: 'You can set up vibrations in a target\u2019s body that, when triggered, can deal massive damage.' },
        ],
      },
      {
        key: 'way-of-shadow',
        name: 'Way of Shadow',
        features: [
          { level: 3, name: 'Shadow Arts', description: 'You can use your ki to duplicate the effects of certain spells that create or manipulate darkness and shadows.' },
          { level: 6, name: 'Cloak of Shadows', description: 'You can become invisible in dim light or darkness as a bonus action.' },
          { level: 11, name: 'Opportunist', description: 'You can take advantage of enemies that are distracted or blinded by darkness to strike more effectively.' },
          { level: 17, name: 'Shadow Step Mastery', description: 'Your command of shadow lets you teleport between areas of dim light and strike with precision.' },
        ],
      },
      {
        key: 'way-of-the-four-elements',
        name: 'Way of the Four Elements',
        features: [
          { level: 3, name: 'Elemental Disciplines', description: 'You learn to manifest special elemental techniques that use ki to produce magical effects.' },
          { level: 6, name: 'Elemental Mastery', description: 'You gain improved control over your chosen disciplines, reducing ki costs or increasing potency.' },
          { level: 11, name: 'Elemental Attunement', description: 'Your connection to the elements grants you resistances or movement options tied to element type.' },
          { level: 17, name: 'Perfected Element', description: 'One of your elemental disciplines becomes significantly more powerful.' },
        ],
      },
    ],
  },
  {
    key: 'paladin',
    name: 'Paladin',
    hitDie: 10,
    savingThrows: ['wisdom', 'charisma'],
    armorProficiencies: ['Light armor', 'Medium armor', 'Heavy armor', 'Shields'],
    weaponProficiencies: ['Simple weapons', 'Martial weapons'],
    toolProficiencies: [],
    skillChoices: { count: 2, options: ['athletics', 'insight', 'intimidation', 'medicine', 'persuasion', 'religion'] },
    startingEquipment: {
      choices: [
        { options: [{ items: ['A martial weapon and a shield'] }, { items: ['Two martial weapons'] }] },
        { options: [{ items: ['Five javelins'] }, { items: ['Any simple melee weapon'] }] },
        { options: [{ items: ['A priest\u2019s pack'] }, { items: ['An explorer\u2019s pack'] }] },
      ],
      fixed: ['Chain mail', 'A holy symbol'],
    },
    spellcasting: { ability: 'charisma', type: 'half', knownOrPrepared: 'prepared', focus: 'holy symbol' },
    features: [
      { level: 1, name: 'Divine Sense', description: 'You can use your action to detect the presence of celestial, fiend, or undead creatures within 60 feet.' },
      { level: 1, name: 'Lay on Hands', description: 'Your blessed touch can heal wounds, drawing from a pool of healing power that replenishes after a long rest.' },
      { level: 2, name: 'Fighting Style', description: 'You adopt a particular style of fighting as your specialty.' },
      { level: 2, name: 'Spellcasting', description: 'You have learned to draw on divine magic through prayer and meditation to cast spells as a cleric does.' },
      { level: 2, name: 'Divine Smite', description: 'When you hit a creature with a melee weapon attack, you can expend a spell slot to deal extra radiant damage.' },
      { level: 3, name: 'Divine Health', description: 'The divine magic flowing through you makes you immune to disease.' },
      { level: 3, name: 'Sacred Oath', description: 'You swear the oath that binds you as a paladin forever, granting oath spells and Channel Divinity options.', isSubclassChoice: true },
      { level: 5, name: 'Extra Attack', description: 'You can attack twice, instead of once, whenever you take the Attack action on your turn.' },
      { level: 6, name: 'Aura of Protection', description: 'You and friendly creatures within 10 feet add your Charisma modifier to saving throws.' },
      { level: 10, name: 'Aura of Courage', description: 'You and friendly creatures within 10 feet can\u2019t be frightened while you are conscious.' },
      { level: 11, name: 'Improved Divine Smite', description: 'All of your melee weapon strikes carry divine power, adding extra radiant damage on every hit.' },
      { level: 14, name: 'Cleansing Touch', description: 'You can use your action to end one spell on yourself or on one willing creature that you touch.' },
    ],
    subclasses: [
      {
        key: 'oath-of-devotion',
        name: 'Oath of Devotion',
        features: [
          { level: 3, name: 'Channel Divinity: Sacred Weapon', description: 'You can imbue one weapon you are holding with positive energy, adding your Charisma modifier to attack rolls and causing it to emit light.' },
          { level: 3, name: 'Channel Divinity: Turn the Unholy', description: 'You can use Channel Divinity to turn fiends and undead.' },
          { level: 7, name: 'Aura of Devotion', description: 'You and friendly creatures within 10 feet can\u2019t be charmed while you are conscious.' },
          { level: 15, name: 'Purity of Spirit', description: 'You are always under the effects of a protection from evil and good spell.' },
          { level: 20, name: 'Holy Nimbus', description: 'You can emanate an aura of sunlight that damages fiends and undead and gives you and allies advantage on saves against spells cast by fiends or undead.' },
        ],
      },
      {
        key: 'oath-of-vengeance',
        name: 'Oath of Vengeance',
        features: [
          { level: 3, name: 'Channel Divinity: Abjure Enemy', description: 'You can use your Channel Divinity to frighten or impede a foe, giving you an edge in pursuit.' },
          { level: 3, name: 'Vow of Enmity', description: 'You can utter a vow to focus your wrath on a single creature, gaining advantage on attack rolls against it for a short time.' },
          { level: 7, name: 'Relentless Avenger', description: 'When you hit a creature, you can move up to half your speed without provoking opportunity attacks.' },
          { level: 15, name: 'Soul of Vengeance', description: 'Your divine wrath allows you to continue fighting through great harm.' },
          { level: 20, name: 'Avenging Angel', description: 'You assume an aspect of an avenging angel to mete out justice against your foes.' },
        ],
      },
      {
        key: 'oath-of-the-crown',
        name: 'Oath of the Crown',
        features: [
          { level: 3, name: 'Channel Divinity: Champion Challenge', description: 'You can compel enemies to engage you, punishing those who flee or ignore rightful authority.' },
          { level: 7, name: 'Divine Allegiance', description: 'You can swap damage taken by an ally with yourself, shielding the loyal.' },
          { level: 15, name: 'Divine Presence', description: 'Your presence bolsters allies and punishes foes in defense of order.' },
          { level: 20, name: 'Imperial Champion', description: 'You become an avatar of law and order on the battlefield.' },
        ],
      },
      {
        key: 'oath-of-conquest',
        name: 'Oath of Conquest',
        features: [
          { level: 3, name: 'Channel Divinity: Conquering Presence', description: 'You can strike fear into the hearts of foes, slowing their advance.' },
          { level: 7, name: 'Scornful Rebuke', description: 'When struck, you can respond with punishing force that deters attackers.' },
          { level: 15, name: 'Aura of Conquest', description: 'Your presence saps the will of nearby enemies, imposing penalties on their attacks and movement.' },
          { level: 20, name: 'Invincible Conqueror', description: 'You become an unstoppable force of domination on the field of battle.' },
        ],
      },
      {
        key: 'oath-of-the-ancients',
        name: 'Oath of the Ancients',
        features: [
          { level: 3, name: 'Channel Divinity: Nature\'s Wrath', description: 'You can channel nature to ensnare or hinder foes.' },
          { level: 7, name: 'Aura of Warding', description: 'You and allies near you gain resistance to spell damage.' },
          { level: 15, name: 'Undying Sentinel', description: 'Your resilience in defense of life grows, restoring and protecting nearby allies.' },
          { level: 20, name: 'Elder Champion', description: 'You take on an aspect of ancient power, blessing allies and blighting foes.' },
        ],
      },
      {
        key: 'oath-of-redemption',
        name: 'Oath of Redemption',
        features: [
          { level: 3, name: 'Channel Divinity: Emissary of Peace', description: 'You can use your Channel Divinity to calm violence, imposing nonlethal penalties.' },
          { level: 7, name: 'Rebuke the Violent', description: 'When a creature attacks an ally, you can use your reaction to deal radiant damage and reduce their momentum.' },
          { level: 15, name: 'Protective Spirit', description: 'Your defense of others grows stronger, absorbing harm meant for them.' },
          { level: 20, name: 'Savior\'s Grace', description: 'You become a paragon of peace, granting powerful protective effects to allies.' },
        ],
      },
    ],
  },
  {
    key: 'ranger',
    name: 'Ranger',
    hitDie: 10,
    savingThrows: ['strength', 'dexterity'],
    armorProficiencies: ['Light armor', 'Medium armor', 'Shields'],
    weaponProficiencies: ['Simple weapons', 'Martial weapons'],
    toolProficiencies: [],
    skillChoices: { count: 3, options: ['animalHandling', 'athletics', 'insight', 'investigation', 'nature', 'perception', 'stealth', 'survival'] },
    startingEquipment: {
      choices: [
        { options: [{ items: ['Scale mail'] }, { items: ['Leather armor'] }] },
        { options: [{ items: ['Two shortswords'] }, { items: ['Two simple melee weapons'] }] },
        { options: [{ items: ['A dungeoneer\u2019s pack'] }, { items: ['An explorer\u2019s pack'] }] },
      ],
      fixed: ['A longbow', 'A quiver of 20 arrows'],
    },
    spellcasting: { ability: 'wisdom', type: 'half', knownOrPrepared: 'known', focus: null },
    features: [
      { level: 1, name: 'Favored Enemy', description: 'You have significant experience studying, tracking, hunting, and even talking to a certain type of enemy.' },
      { level: 1, name: 'Natural Explorer', description: 'You are particularly familiar with one type of natural environment and adept at traveling and surviving in such regions.' },
      { level: 2, name: 'Fighting Style', description: 'You adopt a particular style of fighting as your specialty.' },
      { level: 2, name: 'Spellcasting', description: 'You have learned to use the magical essence of nature to cast spells, much as a druid does.' },
      { level: 3, name: 'Ranger Archetype', description: 'Choose an archetype that you emulate in the exercise of your ranger abilities.', isSubclassChoice: true },
      { level: 3, name: 'Primeval Awareness', description: 'You can expend a spell slot to sense whether certain types of creatures are present within 1 mile.' },
      { level: 5, name: 'Extra Attack', description: 'You can attack twice, instead of once, whenever you take the Attack action on your turn.' },
      { level: 8, name: 'Land\u2019s Stride', description: 'Moving through nonmagical difficult terrain costs you no extra movement, and you have advantage on saves against plants that impede movement.' },
      { level: 10, name: 'Hide in Plain Sight', description: 'You can spend 1 minute creating camouflage for yourself, gaining a bonus to Stealth checks as long as you remain still.' },
      { level: 14, name: 'Vanish', description: 'You can use the Hide action as a bonus action, and you can\u2019t be tracked by nonmagical means unless you choose to leave a trail.' },
      { level: 18, name: 'Feral Senses', description: 'You gain preternatural senses that help you fight creatures you can\u2019t see, including the ability to attack invisible creatures without disadvantage.' },
      { level: 20, name: 'Foe Slayer', description: 'Once per turn you can add your Wisdom modifier to the attack roll or damage roll of an attack you make against one of your favored enemies.' },
    ],
    subclasses: [
      {
        key: 'hunter',
        name: 'Hunter',
        features: [
          { level: 3, name: 'Hunter\u2019s Prey', description: 'Choose a feature, such as Colossus Slayer, Giant Killer, or Horde Breaker, that gives you a combat option against your prey.' },
          { level: 7, name: 'Defensive Tactics', description: 'Choose a feature, such as Escape the Horde, Multiattack Defense, or Steel Will, that helps you survive battles against multiple foes or powerful single enemies.' },
          { level: 11, name: 'Multiattack', description: 'Choose Volley or Whirlwind Attack to improve your attacks against multiple nearby creatures.' },
          { level: 15, name: 'Superior Hunter\u2019s Defense', description: 'Choose a defensive feature, such as Evasion, Stand Against the Tide, or Uncanny Dodge.' },
        ],
      },
      {
        key: 'beast-master',
        name: 'Beast Master',
        features: [
          { level: 3, name: 'Ranger\'s Companion', description: 'You gain a faithful animal companion that fights alongside you.' },
          { level: 7, name: 'Exceptional Training', description: 'Your bond with your companion deepens, allowing better teamwork and sharing of actions.' },
          { level: 11, name: 'Superior Bond', description: 'Your animal companion gains improved statistics and abilities.' },
          { level: 15, name: 'Bestial Guardian', description: 'Your companion becomes more resilient and effective in combat.' },
        ],
      },
    ],
  },
  {
    key: 'rogue',
    name: 'Rogue',
    hitDie: 8,
    savingThrows: ['dexterity', 'intelligence'],
    armorProficiencies: ['Light armor'],
    weaponProficiencies: ['Simple weapons', 'Hand crossbows', 'Longswords', 'Rapiers', 'Shortswords'],
    toolProficiencies: ["Thieves' tools"],
    skillChoices: { count: 4, options: ['acrobatics', 'athletics', 'deception', 'insight', 'intimidation', 'investigation', 'perception', 'performance', 'persuasion', 'sleightOfHand', 'stealth'] },
    startingEquipment: {
      choices: [
        { options: [{ items: ['A rapier'] }, { items: ['A shortsword'] }] },
        { options: [{ items: ['A shortbow and quiver of 20 arrows'] }, { items: ['A shortsword'] }] },
        { options: [{ items: ['A burglar\u2019s pack'] }, { items: ['A dungeoneer\u2019s pack'] }, { items: ['An explorer\u2019s pack'] }] },
      ],
      fixed: ['Leather armor', 'A dagger', 'Thieves\u2019 tools'],
    },
    spellcasting: null,
    features: [
      { level: 1, name: 'Expertise', description: 'Choose two of your skill proficiencies (or one and Thieves\u2019 Tools). Your proficiency bonus is doubled for any ability check using either of them.' },
      { level: 1, name: 'Sneak Attack', description: 'Once per turn, you can deal extra damage to one creature you hit with an attack if you have advantage on the attack roll, or if another enemy of the target is within 5 feet of it.' },
      { level: 1, name: 'Thieves\u2019 Cant', description: 'You have learned thieves\u2019 cant, a secret mix of dialect, jargon, and code that allows you to hide messages in seemingly normal conversation.' },
      { level: 2, name: 'Cunning Action', description: 'You can take a bonus action on each of your turns to Dash, Disengage, or Hide.' },
      { level: 3, name: 'Roguish Archetype', description: 'Choose an archetype that you emulate in the exercise of your rogue abilities.', isSubclassChoice: true },
      { level: 5, name: 'Uncanny Dodge', description: 'When an attacker that you can see hits you with an attack, you can use your reaction to halve the attack\u2019s damage against you.' },
      { level: 7, name: 'Evasion', description: 'When subjected to an effect allowing a Dexterity save for half damage, you take no damage on a success and only half on a failure.' },
      { level: 11, name: 'Reliable Talent', description: 'Whenever you make an ability check that lets you add your proficiency bonus, treat a d20 roll of 9 or lower as a 10.' },
      { level: 14, name: 'Blindsense', description: 'If you are able to hear, you are aware of the location of any hidden or invisible creature within 10 feet of you.' },
      { level: 15, name: 'Slippery Mind', description: 'You gain proficiency in Wisdom saving throws.' },
      { level: 18, name: 'Elusive', description: 'No attack roll has advantage against you while you aren\u2019t incapacitated.' },
      { level: 20, name: 'Stroke of Luck', description: 'If your attack misses a target within range, you can turn the miss into a hit, or if you fail an ability check, you can treat it as a 20.' },
    ],
    subclasses: [
      {
        key: 'thief',
        name: 'Thief',
        features: [
          { level: 3, name: 'Fast Hands', description: 'You can use the bonus action granted by Cunning Action to make a Sleight of Hand check, use thieves\u2019 tools, or take the Use an Object action.' },
          { level: 3, name: 'Second-Story Work', description: 'Climbing no longer costs you extra movement, and when you make a running jump, the distance you cover increases by your Dexterity modifier.' },
          { level: 9, name: 'Supreme Sneak', description: 'You have advantage on Stealth checks if you move no more than half your speed on the same turn.' },
          { level: 13, name: 'Use Magic Device', description: 'You ignore all class, race, and level requirements on the use of magic items.' },
          { level: 17, name: 'Thief\u2019s Reflexes', description: 'You can take two turns during the first round of any combat, taking your second turn at your normal initiative minus 10.' },
        ],
      },
      {
        key: 'assassin',
        name: 'Assassin',
        features: [
          { level: 3, name: 'Assassinate', description: 'You are adept at striking foes who are surprised, dealing extra damage and gaining advantage in those situations.' },
          { level: 9, name: 'Infiltration Expertise', description: 'You can adopt disguises and false identities, enabling deep-cover operations.' },
          { level: 13, name: 'Impostor', description: 'You can mimic the speech and behavior of others closely to deceive targets.' },
          { level: 17, name: 'Death Strike', description: 'Your precision in striking vital areas improves, increasing critical potential.' },
        ],
      },
      {
        key: 'arcane-trickster',
        name: 'Arcane Trickster',
        features: [
          { level: 3, name: 'Spellcasting', description: 'You learn a limited selection of wizard spells to augment your thievery.' },
          { level: 9, name: 'Magical Ambush', description: 'You can deploy spells in ambushes to catch foes off guard.' },
          { level: 13, name: 'Versatile Trickster', description: 'You can use magic to distract and confuse foes, improving your sneak attack opportunities.' },
          { level: 17, name: 'Spell Thief', description: 'You can steal the knowledge of spells from other casters in certain circumstances.' },
        ],
      },
    ],
  },
  {
    key: 'sorcerer',
    name: 'Sorcerer',
    hitDie: 6,
    savingThrows: ['constitution', 'charisma'],
    armorProficiencies: [],
    weaponProficiencies: ['Daggers', 'Darts', 'Slings', 'Quarterstaffs', 'Light crossbows'],
    toolProficiencies: [],
    skillChoices: { count: 2, options: ['arcana', 'deception', 'insight', 'intimidation', 'persuasion', 'religion'] },
    startingEquipment: {
      choices: [
        { options: [{ items: ['A light crossbow and 20 bolts'] }, { items: ['Any simple weapon'] }] },
        { options: [{ items: ['A component pouch'] }, { items: ['An arcane focus'] }] },
        { options: [{ items: ['A dungeoneer\u2019s pack'] }, { items: ['An explorer\u2019s pack'] }] },
      ],
      fixed: ['Two daggers'],
    },
    spellcasting: { ability: 'charisma', type: 'full', knownOrPrepared: 'known', focus: 'arcane focus' },
    features: [
      { level: 1, name: 'Spellcasting', description: 'An event in your past, or in the life of a parent or ancestor, left an indelible mark on you, infusing you with arcane magic.' },
      { level: 1, name: 'Sorcerous Origin', description: 'Choose a source of your innate magical ability, which determines additional features as you gain levels.', isSubclassChoice: true },
      { level: 2, name: 'Font of Magic', description: 'You gain sorcery points that you can use to create spell slots or fuel metamagic options.' },
      { level: 3, name: 'Metamagic', description: 'You gain the ability to twist your spells to suit your needs, choosing two Metamagic options such as Twinned Spell or Quickened Spell.' },
      { level: 20, name: 'Sorcerous Restoration', description: 'You regain 4 sorcery points whenever you finish a short rest.' },
    ],
    subclasses: [
      {
        key: 'draconic-bloodline',
        name: 'Draconic Bloodline',
        features: [
          { level: 1, name: 'Dragon Ancestor', description: 'Choose a type of dragon as your ancestor, determining the damage type for some of your bloodline abilities.' },
          { level: 1, name: 'Draconic Resilience', description: 'Your hit point maximum increases by 1, and increases again every time you gain a sorcerer level. Your skin gets a scaly sheen and your AC equals 13 + Dexterity modifier when not wearing armor.' },
          { level: 6, name: 'Elemental Affinity', description: 'When you cast a spell that deals damage of the type associated with your draconic ancestry, you can add your Charisma modifier to one damage roll.' },
          { level: 14, name: 'Dragon Wings', description: 'You can use a bonus action to grow dragon wings, giving you a flying speed equal to your current speed.' },
          { level: 18, name: 'Draconic Presence', description: 'You can spend an action to channel the dread presence of your dragon ancestor, causing creatures of your choice within 60 feet to become frightened or charmed.' },
        ],
      },
      {
        key: 'wild-magic',
        name: 'Wild Magic',
        features: [
          { level: 1, name: 'Wild Surge', description: 'You may trigger unpredictable magical effects when you cast spells.' },
          { level: 6, name: 'Tides of Chaos', description: 'You can gain advantage on an attack or ability check; the DM may call on you to roll on the wild magic table.' },
          { level: 14, name: 'Bend Luck', description: 'You can influence the outcome of others\' rolls by spending a reaction.' },
          { level: 18, name: 'Controlled Chaos', description: 'You gain greater control over wild magic surges, channeling the chaos deliberately.' },
        ],
      },
    ],
  },
  {
    key: 'warlock',
    name: 'Warlock',
    hitDie: 8,
    savingThrows: ['wisdom', 'charisma'],
    armorProficiencies: ['Light armor'],
    weaponProficiencies: ['Simple weapons'],
    toolProficiencies: [],
    skillChoices: { count: 2, options: ['arcana', 'deception', 'history', 'intimidation', 'investigation', 'nature', 'religion'] },
    startingEquipment: {
      choices: [
        { options: [{ items: ['A light crossbow and 20 bolts'] }, { items: ['Any simple weapon'] }] },
        { options: [{ items: ['A component pouch'] }, { items: ['An arcane focus'] }] },
        { options: [{ items: ['A scholar\u2019s pack'] }, { items: ['A dungeoneer\u2019s pack'] }] },
      ],
      fixed: ['Leather armor', 'Any simple weapon', 'Two daggers'],
    },
    spellcasting: { ability: 'charisma', type: 'pact', knownOrPrepared: 'known', focus: 'arcane focus' },
    features: [
      { level: 1, name: 'Otherworldly Patron', description: 'You have struck a bargain with an otherworldly being of your choice, who grants you magical abilities.', isSubclassChoice: true },
      { level: 1, name: 'Pact Magic', description: 'Your arcane research and the magic bestowed on you by your patron have given you facility with spells, drawn from a small, limited pool of spell slots that recharge on a short rest.' },
      { level: 2, name: 'Eldritch Invocations', description: 'You gain access to special boons granted by your patron, such as Agonizing Blast or Devil\u2019s Sight, called eldritch invocations.' },
      { level: 3, name: 'Pact Boon', description: 'Your patron bestows a gift upon you for your loyal service: the Pact of the Blade, Chain, or Tome.' },
      { level: 11, name: 'Mystic Arcanum', description: 'Your patron bestows upon you a magical secret called an arcanum, a spell that you can cast once per long rest without expending a spell slot.' },
      { level: 20, name: 'Eldritch Master', description: 'You can draw on your inner reserve of mystical power while entreating your patron to regain expended spell slots.' },
    ],
    subclasses: [
      {
        key: 'the-fiend',
        name: 'The Fiend',
        features: [
          { level: 1, name: 'Dark One\u2019s Blessing', description: 'When you reduce a hostile creature to 0 hit points, you gain temporary hit points equal to your Charisma modifier plus your warlock level.' },
          { level: 6, name: 'Dark One\u2019s Own Luck', description: 'You can call on your patron to alter fate in your favor, adding a bonus to one ability check or saving throw.' },
          { level: 10, name: 'Fiendish Resilience', description: 'You can choose one damage type when you finish a short or long rest, becoming resistant to that damage type until you choose a different one.' },
          { level: 14, name: 'Hurl Through Hell', description: 'When you hit a creature with an attack, you can use this feature to instantly transport it through the lower planes.' },
        ],
      },
    ],
  },
  // Artificer (Tasha/Eberron) — added source: 'Tasha'
  {
    key: 'artificer',
    name: 'Artificer',
    source: 'Tasha',
    hitDie: 8,
    savingThrows: ['constitution', 'intelligence'],
    armorProficiencies: ['Light armor', 'Medium armor', 'Shields'],
    weaponProficiencies: ['Simple weapons', 'Shortswords', 'Crossbows'],
    toolProficiencies: ["Tinker's tools", "One type of artisan's tools"],
    skillChoices: { count: 2, options: ['arcana', 'history', 'investigation', 'medicine', 'perception', 'sleightOfHand'] },
    startingEquipment: { choices: [], fixed: [] },
    // Artificer uses Intelligence and prepares spells; modeled as 'full' caster for slot progression
    spellcasting: { ability: 'intelligence', type: 'full', knownOrPrepared: 'prepared', focus: 'tools' },
    features: [
      { level: 1, name: 'Magical Tinkering', description: 'Create minor magical effects with your tools.' },
      { level: 2, name: 'Infuse Item', description: 'Imbue items with magical properties.' },
      { level: 3, name: 'Artificer Specialist', description: 'Choose a specialization that grants unique features.' },
    ],
    subclasses: [
      {
        key: 'alchemist',
        name: 'Alchemist',
        features: [
          { level: 3, name: 'Experimental Elixir', description: 'Brew elixirs that grant effects when consumed.' },
        ],
      },
      {
        key: 'artillerist',
        name: 'Artillerist',
        features: [
          { level: 3, name: 'Eldritch Cannon', description: 'Create a magical cannon that attacks or shields.' },
        ],
      },
      {
        key: 'battlesmith',
        name: 'Battle Smith',
        features: [
          { level: 3, name: 'Battle Ready', description: 'Use Intelligence for attacks and enhance a mechanical companion.' },
        ],
      },
      {
        key: 'armorer',
        name: 'Armorer',
        source: 'Tasha',
        features: [
          { level: 3, name: 'Armor Model', description: 'Customize a suit of armor with magical functions.' },
        ],
      },
    ],
  },
  {
    key: 'wizard',
    name: 'Wizard',
    hitDie: 6,
    savingThrows: ['intelligence', 'wisdom'],
    armorProficiencies: [],
    weaponProficiencies: ['Daggers', 'Darts', 'Slings', 'Quarterstaffs', 'Light crossbows'],
    toolProficiencies: [],
    skillChoices: { count: 2, options: ['arcana', 'history', 'insight', 'investigation', 'medicine', 'religion'] },
    startingEquipment: {
      choices: [
        { options: [{ items: ['A quarterstaff'] }, { items: ['A dagger'] }] },
        { options: [{ items: ['A component pouch'] }, { items: ['An arcane focus'] }] },
        { options: [{ items: ['A scholar\u2019s pack'] }, { items: ['An explorer\u2019s pack'] }] },
      ],
      fixed: ['A spellbook'],
    },
    spellcasting: { ability: 'intelligence', type: 'full', knownOrPrepared: 'prepared', focus: 'arcane focus / spellbook' },
    features: [
      { level: 1, name: 'Spellcasting', description: 'As a student of arcane magic, you have a spellbook containing spells that show the first glimmerings of your true power.' },
      { level: 1, name: 'Arcane Recovery', description: 'You have learned to regain some of your magical energy by studying your spellbook, recovering spell slots during a short rest once per day.' },
      { level: 2, name: 'Arcane Tradition', description: 'Choose an arcane tradition, shaping your practice of magic through one of eight schools.', isSubclassChoice: true },
      { level: 18, name: 'Spell Mastery', description: 'You can cast a 1st-level and a 2nd-level spell of your choice at will, without expending a spell slot.' },
      { level: 20, name: 'Signature Spells', description: 'You gain mastery over two 3rd-level spells and can cast them at their lowest level without expending a spell slot, and again before a short or long rest.' },
    ],
    subclasses: [
      {
        key: 'school-of-evocation',
        name: 'School of Evocation',
        features: [
          { level: 2, name: 'Evocation Savant', description: 'The gold and time you must spend to copy an evocation spell into your spellbook is halved.' },
          { level: 2, name: 'Sculpt Spells', description: 'You can create pockets of relative safety within the area of your evocation spells, automatically succeeding allies on the save and taking no damage if they would normally take half on a success.' },
          { level: 6, name: 'Potent Cantrip', description: 'Your damaging cantrips affect even creatures that avoid the brunt of the effect, dealing half damage on a successful save.' },
          { level: 10, name: 'Empowered Evocation', description: 'You can add your Intelligence modifier to one damage roll of any wizard evocation spell you cast.' },
          { level: 14, name: 'Overchannel', description: 'You can increase the power of simpler spells, dealing maximum damage at the cost of personal strain on repeated use.' },
        ],
      },
    ],
  },
];
